### ISSUE TITLE
Use as a toolbox

### ISSUE THREAD

**Issue by KentaItakura** [fr0nkk/matogl#1]
Hi, thank you so much for your excellent work for this repo!! 
Do you have a plan to publish this work as a form of "toolbox"?
I would like to use this visualization like a toolbox and replace `pcshow`  by your function in my environment.

**Comment by fr0nkk** [comment]
Hello and thank you for your kind words!
I just published a toolbox version here : [https://www.mathworks.com/matlabcentral/fileexchange/105545-matlab-opengl-toolbox](https://www.mathworks.com/matlabcentral/fileexchange/105545-matlab-opengl-toolbox)
This is my first time publishing a toolbox, can you confirm if it works? Thanks!!

**Comment by KentaItakura** [comment]
Thank you so much!! I will test it.

**Comment by KentaItakura** [comment]
I have installed the openGL toolbox and worked in 2022a! Thank you!
